# Generated by Django 4.2.1 on 2023-05-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleEarrings', models.CharField(max_length=50, verbose_name='Название')),
                ('metalEarrings', models.TextField(verbose_name='Материал')),
                ('priceEarrings', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Medallion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleMedallion', models.CharField(max_length=50, verbose_name='Название')),
                ('metalMedallion', models.TextField(verbose_name='Материал')),
                ('priceMedallion', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleRing', models.CharField(max_length=50, verbose_name='Название')),
                ('metalRing', models.TextField(verbose_name='Материал')),
                ('priceRing', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
