# Generated by Django 4.2.1 on 2023-05-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_earrings_cat_medallion_cat_ring_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='earrings',
            options={'ordering': ['titleEarrings'], 'verbose_name': 'Серьги'},
        ),
        migrations.AlterModelOptions(
            name='medallion',
            options={'ordering': ['titleMedallion'], 'verbose_name': 'Медальоны'},
        ),
        migrations.AlterModelOptions(
            name='ring',
            options={'ordering': ['titleRing'], 'verbose_name': 'Кольца'},
        ),
    ]
